name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Install Dependencies
      run: npm install

    - name: Build Angular App
      run: npm run build

    - name: Deploy to GitHub Pages
      run: |
        ls -l dist/your-angular-app
        npx angular-cli-ghpages --dir=dist/your-angular-app --no-silent
      env:
        CI: true

        
        
        
        
